package com.restaurant.collection.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

@Data
@NoArgsConstructor
@AllArgsConstructor
@SuperBuilder
public class BaseDto {

    @Schema(description = "Unique id of the restaurant as generated by the system.", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;
}
