server:
  port: 8080

spring:
  application:
    name: "Restaurant Collection"
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
logging:
  level:
    org.springframework: ERROR
    com.andersen.restaurants: INFO
  file:
    name: logs.txt

